version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: beca-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - beca-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: beca-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - beca-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: beca-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - beca-net
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3

  ms-usuarios:
    build: ./ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_usuarios
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - beca-net


  ms-transacoes:
    build:
      context: ./ms-transacoes
      dockerfile: Dockerfile

    container_name: ms-transacoes
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_transacoes
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - beca-net

  ms-processor:
    build:
      context: ./ms-processor
      dockerfile: Dockerfile
    container_name: ms-processor
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_transacoes
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - API_MOCK_URL=http://mock-api:3000
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mock-api:
        condition: service_started
    networks:
      - beca-net

  mock-api:
    image: clue/json-server
    container_name: mock-api
    command: --watch db.json --host 0.0.0.0
    ports:
      - "8090:3000"
    volumes:
      - ./infra/mock-data/db.json:/data/db.json
    networks:
      - beca-net


  prometheus:
    image: prom/prometheus:latest
    container_name: beca-prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - beca-net

  grafana:
    image: grafana/grafana:latest
    container_name: beca-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - beca-net

networks:
  beca-net:
    driver: bridge